# Generated by Django 3.1.3 on 2020-12-28 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201123_1314'),
        ('api', '0002_auto_20201218_1626'),
    ]

    operations = [
    ]
